        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 11:47:55 2024
        MODULE CALCULATION__genmod
          INTERFACE 
            SUBROUTINE CALCULATION
            END SUBROUTINE CALCULATION
          END INTERFACE 
        END MODULE CALCULATION__genmod
